apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  name: prometheus-metrics-viewer
  namespace: openshift-logging
roleRef:
  name: prometheus-metrics-viewer
  namespace: openshift-logging
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: openshift-metrics
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
userNames:
- system:serviceaccount:openshift-metrics:prometheus
- system:serviceaccount:openshift-monitoring:prometheus-k8s
