apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: application-metrics
  name: application-metrics
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    scheme: http
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      scrape: prometheus
